print('Today is a good day!')
print(1+1)
print('1+1')
print("J'aime les pommes, il aime les poires.")
print('---------------')
print("J'aime les pommes, ")
print("il aime les poires.")
print('---------------')
print("J'aime les pommes, \nil aime les poires.")